import { Link } from "react-router";
import { Card, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import type { BlogPost } from "@/lib/definitions";
import { parseISO } from "date-fns/parseISO";
import { format } from "date-fns/format";

interface BlogCardProps {
  blog: BlogPost;
}

export default function BlogCard({ blog }: BlogCardProps) {
  return (
    <Link to={`/blogs/${blog.id}`}>
      <Card className="h-full flex flex-col">
        <CardHeader>
          <CardTitle
            className="text-lg font-semibold line-clamp-3"
            title={blog.title}
          >
            {blog.title}
          </CardTitle>
        </CardHeader>

        <CardFooter className="flex justify-between text-sm text-muted-foreground mt-auto">
          <span>Generated by AI</span>
          <span>{format(parseISO(blog.createdAt), "MMMM d, yyyy")}</span>
        </CardFooter>
      </Card>
    </Link>
  );
}
